name: GIS Decyzje

on:
  schedule:
    - cron: '5 22 * * *'

  workflow_dispatch:

jobs:
  build_gis_ostrzezenia:
    runs-on: ubuntu-latest
    name: GIS Decyzje
    env:
      TEST_CHANNEL_URL: "@gpi_health_check"
      CHANNEL_URL: "@gpi_gis"
    steps:
      - uses: actions/checkout@v2

      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: install requirements
        run: pip install -r requirements.txt
      - name: python script run
        run: |
          python gpi.py
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          GIVEN_DATE: 2021-06-25
          FEED_NAME: GIS Decyzje
          ARTICLE_TYPE: Decyzja
          FEED_URL: https://rdg.ezdrowie.gov.pl
          CHANNEL_URL: ${{ env.CHANNEL_URL }}
          TEST_CHANNEL_URL: ${{ env.TEST_CHANNEL_URL }}