name: Koronawirus Działania rządu

on:
  schedule:
    - cron: '5 22 * * *'

  workflow_dispatch:

jobs:
  build_koronawirus_dzialania_rzadu:
    runs-on: ubuntu-latest
    name: Koronawirus Działania rządu
    env:
      TEST_CHANNEL_URL: "@gpi_health_check"
      CHANNEL_URL: "@gpi_koronawirus"
    steps:
      - uses: actions/checkout@v2

      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: install requirements
        run: pip install -r requirements.txt
      - name: python script run
        run: |
          python gpi.py
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          GIVEN_DATE: today
          FEED_NAME: Koronawirus Działania rządu
          ARTICLE_TYPE: Działanie rządu
          FEED_URL: https://www.gov.pl/web/koronawirus/dzialania-rzadu
          CHANNEL_URL: ${{ env.CHANNEL_URL }}
          TEST_CHANNEL_URL: ${{ env.TEST_CHANNEL_URL }}